-- Create the manga table
-- Note: It seems your existing manga table uses BIGINT for IDs.
-- If the table already exists, this block is skipped.
CREATE TABLE IF NOT EXISTS manga (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    mangadex_id TEXT UNIQUE,
    status TEXT DEFAULT 'ongoing', -- 'ongoing', 'completed', 'on_hold'
    last_known_chapter TEXT, -- Stored as text to handle "10.5" etc.
    last_checked_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    user_id UUID REFERENCES auth.users(id)
);

-- Create the chapters table to store history/updates
CREATE TABLE IF NOT EXISTS chapters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    manga_id BIGINT REFERENCES manga(id) ON DELETE CASCADE, -- Changed to BIGINT to match manga.id
    chapter_number TEXT NOT NULL,
    title TEXT,
    release_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(manga_id, chapter_number)
);

-- Enable Row Level Security (RLS)
ALTER TABLE manga ENABLE ROW LEVEL SECURITY;
ALTER TABLE chapters ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow public read access" ON manga FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update access" ON manga FOR ALL USING (true);

CREATE POLICY "Allow public read access" ON chapters FOR SELECT USING (true);
CREATE POLICY "Allow public insert/update access" ON chapters FOR ALL USING (true);
